let auctionInterval=null;
function getAuctionContext(){const u=requireAuth();if(!u)return null;const d=loadData(),league=currentLeague(u.id);const teams=d.teams.filter(t=>t.leagueId===league?.id);return {u,d,league,teams};}
function getActiveAuction(leagueId){const d=loadData();return d.auctions.find(a=>a.leagueId===leagueId&&a.status==='running')||d.auctions.find(a=>a.leagueId===leagueId&&a.status==='paused')||null;}
function startAuction(leagueId,playerId,starterTeamId){updateData(d=>{const existing=d.auctions.find(a=>a.leagueId===leagueId&&['running','paused'].includes(a.status));if(existing)throw new Error('Esiste già un’asta attiva.');const l=d.leagues.find(x=>x.id===leagueId);d.auctions.push({id:uid('auc'),leagueId,playerId,currentPrice:0,bestTeamId:null,starterTeamId,status:'running',endsAt:Date.now()+l.timer*1000,history:[],createdAt:Date.now()});});}
function placeBid(leagueId,teamId,increment){const d=loadData();const a=getActiveAuction(leagueId);if(!a)throw new Error('Nessuna asta attiva.');const t=d.teams.find(x=>x.id===teamId);const next=a.currentPrice+Number(increment);if(next>t.credits)throw new Error('Crediti insufficienti.');a.currentPrice=next;a.bestTeamId=teamId;a.endsAt=Date.now()+d.leagues.find(x=>x.id===leagueId).timer*1000;a.history.push({teamId,amount:next,at:Date.now()});saveData(d);}
function settleAuction(leagueId){const d=loadData();const a=getActiveAuction(leagueId);if(!a)return;const p=d.players.find(x=>x.id===a.playerId);if(a.bestTeamId){const t=d.teams.find(x=>x.id===a.bestTeamId);t.credits-=a.currentPrice;t.spent=(t.spent||0)+a.currentPrice;t.players.push(p.id);p.available=false;p.price=a.currentPrice;d.bids.push({id:uid('bid'),auctionId:a.id,leagueId,playerId:p.id,teamId:t.id,price:a.currentPrice,at:Date.now()});d.rosters.push({teamId:t.id,playerId:p.id,price:a.currentPrice,at:Date.now()});}a.status='finished';a.finishedAt=Date.now();saveData(d);}
function cancelAuction(leagueId){updateData(d=>{const a=d.auctions.find(x=>x.leagueId===leagueId&&['running','paused'].includes(x.status));if(a)a.status='cancelled';});}
function pauseAuction(leagueId){updateData(d=>{const a=d.auctions.find(x=>x.leagueId===leagueId&&x.status==='running');if(a)a.status='paused';});}
function resumeAuction(leagueId){updateData(d=>{const a=d.auctions.find(x=>x.leagueId===leagueId&&x.status==='paused');if(a){const l=d.leagues.find(x=>x.id===leagueId);a.status='running';a.endsAt=Date.now()+l.timer*1000;}});}
function renderAuction(){const ctx=getAuctionContext();if(!ctx)return;const {d,league,teams}=ctx;const a=getActiveAuction(league.id);const p=a?d.players.find(x=>x.id===a.playerId):null;document.querySelector('[data-auction-state]').textContent=a?(a.status==='running'?'ASTA IN CORSO':'ASTA IN PAUSA'):'PRONTO PER L’ASTA';document.querySelector('[data-player-name]').textContent=p?.name||'Seleziona un giocatore';document.querySelector('[data-player-meta]').textContent=p?`${p.team} · ${p.role}`:'—';document.querySelector('[data-price]').textContent=a?.currentPrice??0;document.querySelector('[data-bidder]').textContent=(a&&a.bestTeamId?teams.find(t=>t.id===a.bestTeamId)?.name:'Nessuna offerta')||'Nessuna offerta';document.querySelector('[data-timer]').textContent=a?Math.max(0,Math.ceil((a.endsAt-Date.now())/1000)):'—';document.querySelector('[data-teams]').innerHTML=teams.map(t=>`<div class="team-line"><div class="team-mark">${t.abbr}</div><div><strong>${escapeHtml(t.name)}</strong><span>${t.credits} CR</span></div><em>${a?.bestTeamId===t.id?'IN TESTA':''}</em></div>`).join('');document.querySelector('[data-history]').innerHTML=(a?.history||[]).slice(-8).reverse().map(h=>{const t=teams.find(x=>x.id===h.teamId);return `<div class="history-row"><span>${escapeHtml(t?.name||'')}</span><b>${h.amount} CR</b><small>${formatTime(h.at)}</small></div>`}).join('')||'<div class="empty">Nessun rilancio</div>';return a;}

document.addEventListener('DOMContentLoaded',async()=>{const ctx=getAuctionContext();if(!ctx)return;const {u,d,league,teams}=ctx;if(!league){location.href='scelta-lega.html';return;}const players=await loadPlayers();const select=document.querySelector('[data-player-select]');select.innerHTML=players.filter(p=>p.available).map(p=>`<option value="${p.id}">${p.name} — ${p.team} · ${p.role}</option>`).join('');document.querySelector('[data-start]').addEventListener('click',()=>{try{startAuction(league.id,select.value,currentTeam(u.id,league.id)?.id);renderAuction();}catch(e){alert(e.message)}});document.querySelectorAll('[data-bid]').forEach(b=>b.addEventListener('click',()=>{try{placeBid(league.id,currentTeam(u.id,league.id).id,b.dataset.bid);renderAuction();}catch(e){alert(e.message)}}));document.querySelector('[data-pause]').addEventListener('click',()=>{pauseAuction(league.id);renderAuction()});document.querySelector('[data-resume]').addEventListener('click',()=>{resumeAuction(league.id);renderAuction()});document.querySelector('[data-cancel]').addEventListener('click',()=>{cancelAuction(league.id);renderAuction()});document.querySelector('[data-confirm]').addEventListener('click',()=>{settleAuction(league.id);renderAuction();});renderAuction();if(auctionInterval)clearInterval(auctionInterval);auctionInterval=setInterval(()=>{const a=renderAuction();if(a&&a.status==='running'&&Date.now()>=a.endsAt){settleAuction(league.id);renderAuction();}},500);window.addEventListener('storage',renderAuction);window.addEventListener('app:update',renderAuction);});
